### PR TITLE
compile with RelWithDebInfo

### PR DESCRIPTION
**Pull request by muelli**
fixes https://github.com/flathub/org.wireshark.Wireshark/issues/93

### CODE REVIEW

**Comment by Erick555** [comment]
The `-g` flag is always inherited from default flags so all debug symbols were already there and this change results only with drop of `-O3` flag.

BTW: I recommend to disable f-e-d-c if all the PRs are ignored: https://github.com/flathub/org.wireshark.Wireshark/pulls

**Comment by muelli** [comment]
> BTW: I recommend to disable f-e-d-c if all the PRs are ignored: https://github.com/flathub/org.wireshark.Wireshark/pulls

if you look at them you see that they failed compilation due to a bug in Wireshark. But I applied a patch and now all the dependencies are updated.

**Comment by muelli** [comment]
> The `-g` flag is always inherited from default flags so all debug symbols were already there and this change results only with drop of `-O3` flag (which still may make sense).

So are you saying that asking for RelWithDebInfo isn't useful? Neither here nor generally? I genuinely don't know and just listened to what I was told on [another occasion](https://github.com/flathub/flathub/pull/3280#discussion_r902557825). I'm more than happy when not having to carry those extra definitions along.

**Comment by muelli** [comment]
so Release is more clever. Alright, let me change it back, then.

**Comment by muelli** [comment]
60e9b7355e4dc71a0bf9a616518854b1b99695b8

**Comment by Erick555** [comment]
Well, I wrote:

> Using RelWithDebInfo **is right thing** because it gets you -DNDEBUG without changing default optimization level.

If you don't know why you need to change optimization level then perhaps you don't need it.

**Pull request merged**
