### PR TITLE
--share=ipc,--socket=wayland,--filesystem=host:ro

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by muelli** [comment]
do you care to explain your changes a little?

I don't like the `host:ro` part, because parsing untrusted input has been proven to be difficult, at least. I would not like my casual pcap viewer to steal my minesweeper highscore.
Do we know why the portal is not working? Is that due to a custom file picker widget? If so, can we raise it with upstream before making this change on the flatpaked app?

**Comment by eszlari** [comment]
`--share=ipc` is always used together with `--socket=x11` (for performance).


> Do we know why the portal is not working? Is that due to a custom file picker widget?

I don't know. Maybe @grulja has an idea.

**Comment by grulja** [comment]
> > Do we know why the portal is not working? Is that due to a custom file picker widget?
> 
> I don't know. Maybe @grulja has an idea.

It's because their custom file dialog used QFileDialog::DontUseNativeDialog. You need native dialog to be used for portal support.

**Comment by Lekensteyn** [comment]
> It's because their custom file dialog used QFileDialog::DontUseNativeDialog. You need native dialog to be used for portal support.

That flag is set due to additions such as:
- Open dialog: offer a "preview", includes additional information such as file type, start/stop times and packet count
- Save dialog: offer an option to compress the result

The non-native dialog looks like cr*p on KDE, so perhaps this could be changed in the future as an option.

**Comment by Lekensteyn** [comment]
I've opened a bug report to track the use of native file dialog:
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15507

It looks like there are more dialogs (such as "Export dissections") which add even more controls to the save dialog which are essential for functionality of said dialog.

**Comment by muelli** [comment]
> I've opened a bug report to track the use of native file dialog:
> https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15507

cool. thanks.

@eszlari do you think it makes sense to have the public folder writeable s.t. the user can export a pcap file? If so, can you make the change?  I have taken the ipc and wayland change meanwhile.

**Comment by eszlari** [comment]
> do you think it makes sense to have the public folder writeable s.t. the user can export a pcap file? If so, can you make the change?

It's a long time since I last used Wirehark, but isn't capture support needed for this?

**Comment by Lekensteyn** [comment]
> It's a long time since I last used Wireshark, but isn't capture support needed for this?

Users can open a capture file, filter packets, add comments and save the result. This does not require capture support.

Aside from the standard "local capture" options, there are also interfaces like "sshdump" which allows the user to connect to a SSH server, run tcpdump/dumpcap over SSH and receive a packet capture back over the pipe.

**Comment by crondaemon** [comment]
> Users can open a capture file, filter packets, add comments and save the result. This does not require capture support.
> 
> Aside from the standard "local capture" options, there are also interfaces like "sshdump" which allows the user to connect to a SSH server, run tcpdump/dumpcap over SSH and receive a packet capture back over the pipe.

There are many other examples of saving files without capture support:
- open a file in a format and save it in another
- use randpktdump (random packet generator)
- use udpdump (listen on a user socket for incoming packets)
just to cite a few. All of them don't require high privileges. I think it's definitely worth having a way to save local files.

**Comment by muelli** [comment]
I've added read-only permissions for the home directory in addition to the read-write permissions for the public folder.

**Pull request closed without merging**
