### PR TITLE
wireshark-3.0.3

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by muelli** [comment]
Thanks for having noticed the new release. I have subscribed to the github mirror, but it doesn't notify me on pure tags, it seems.

hrm. the appdata fix isn't going to last long :-/ I think either patches or vendorising the appdata file will be more future-proof. My gut feeling says that vendorising is the easiest thing. What do you think?

Anyway, can you propose the additions to the appdata file upstream?

**Comment by eszlari** [comment]
> the appdata fix isn't going to last long

Why? The isn't much activity around that file:
https://github.com/wireshark/wireshark/commits/master/wireshark.appdata.xml

> Anyway, can you propose the additions to the appdata file upstream?

Maybe when I have the time.


Anyway, this is no reason for not merging this!

**Comment by muelli** [comment]
> > the appdata fix isn't going to last long
> 
> Why? There isn't much activity around that file:

because the next release will be more painful to add.

I have thought a little and by now I prefer actual patches to the upstream file. Those can be included as source http://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#idm1213 and allow for easy adoption of upstream.



> Anyway, this is no reason for not merging this!

I beg to differ. I'd argue that an inline script which manipulates XML is difficult to maintain. More difficult than a real patch. And stuff that is hard to maintain is a reason to not merge.

But let me merge it right away. I hope you will find the time to remove the inline script and make it a proper patch, i.e. git commit and git format-patch.

**Comment by eszlari** [comment]
> because the next release will be more painful to add.

Why? You can update the version and date in the same file in that you update the URL and SHA.

**Comment by Lekensteyn** [comment]
We could try to generate that file during the build process and bump the release date and version if that helps. A patch with the expected format is welcome, we can try to adjust the release/build scripts as needed.

**Comment by eszlari** [comment]
https://ask.wireshark.org/question/5784/should-we-migrate-development-to-gitlab/

Hopefully, you will complete a transition to gitlab soon, because that would make contributing easier.

**Comment by eszlari** [comment]
You could copy it form here:

https://github.com/olive-editor/olive/blob/b7a8df26fbb5847fc97ff7cae312f12315ba8859/app/packaging/linux/CMakeLists.txt

**Comment by muelli** [comment]
> > because the next release will be more painful to add.
> 
> Why? You can update the version and date in the same file in that you update the URL and SHA.

nah. It's a "releases" tag. It is supposed to contain all the releases. Not just the last one. Even a call to xmlstarlet would be easier to maintain than this sed call. But patches are best, because then it'll be obvious once the underlying appdata file has changed enough to break the patch. And upstream can incorporate it. And that should be our other main goal: to upstream those modification so that other ecosystems can benefit from it, too.
So, pretty please, if you find the time, a proper patch to the upstream appdata file is appreciated.

**Comment by eszlari** [comment]
>  It is supposed to contain all the releases

Flathub.org only shows the latest release, so what's the point?

> Even a call to xmlstarlet would be easier to maintain than this sed call.

xmlstarlet is not in the SDK.

**Comment by muelli** [comment]
> Flathub.org only shows the latest release, so what's the point?

that is not the only interface to that particular package. For example, GNOME Software exists and it shows the apps based on their appdata file. And if the file is upstream, then more interfaces to the  non-flatpaked version exist.



> xmlstarlet is not in the SDK.

right. I think that maintaining the xmlstarlet dependency and the call to xmlstarlet is still easier than maintaining the inline sed call. But, again, easiest is the actual patch.

**Comment by muelli** [comment]
> We could try to generate that file during the build process and bump the release date and version if that helps.

Cool. If the NEWS file was according to the liking of appstream-util, you could simply use `appstream-util news-to-appdata`. Until then, a tool as in https://github.com/endlessm/flatpak-external-data-checker/issues/17  might be needed.  I'm independently working on something for manipulating appstream files.

> A patch with the expected format is welcome, we can try to adjust the release/build scripts as needed.

@Lekensteyn 
I have pushed https://github.com/flathub/org.wireshark.Wireshark/blob/230d17b85481332dffa980cf9c66b36dbf284cdc/0001-appdata-added-name-and-summary.patch as well as https://github.com/flathub/org.wireshark.Wireshark/blob/230d17b85481332dffa980cf9c66b36dbf284cdc/0002-appdata-Added-releases-to-appdata-file.patch

Let me know if I can change the patches so that they are more likely to get accepted upstream.

**Comment by muelli** [comment]
I may have pushed the changes to the Wireshark gerrit...

```
$ git push gerrit HEAD:refs/for/master/appdata
Counting objects: 12, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 1.61 KiB | 1.61 MiB/s, done.
Total 12 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8)
remote: Processing changes: new: 4, refs: 4, done    
remote: 
remote: New Changes:
remote:   https://code.wireshark.org/review/34546 appdata: added name and summary
remote:   https://code.wireshark.org/review/34547 appdata: Added releases to appdata file
remote:   https://code.wireshark.org/review/34548 appdata: rename updatecontact to update_contact to be more compliant
remote:   https://code.wireshark.org/review/34549 appdata: added 3.0.4 release
remote: 
To ssh://code.wireshark.org:29418/wireshark
 * [new branch]            HEAD -> refs/for/master/appdata
```

**Pull request merged**
