### PR TITLE
wireshark: Update wireshark source from 4.2.6 to 4.4.0

### PR DESCRIPTION
**Pull request by hknaack**

### CODE REVIEW

**Comment by muelli** [comment]
```
========================================================================
Building module wireshark in /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/wireshark-1
========================================================================
]2;flatpak-builder: Building wiresharkFB: Running: tar xf /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/downloads/ead5cdcc08529a2e7ce291e01defc3b0f8831ba24c938db0762b1ebc59c71269/wireshark-4.4.0.tar.xz --no-same-owner --strip-components=1 -J
Applying patch 0001-Add-a-developer-name-tag.patch
FB: Running: patch -p1 -i /srv/buildbot/worker/build-x86_64-7/build/0001-Add-a-developer-name-tag.patch
patching file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml.rej
patching file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml.rej
]2;flatpak-builder: Cleanup wiresharkError: module wireshark: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-gNs8SE
program finished with exit code 1
```

Are the patches upstream?

**Comment by hknaack** [comment]
I compared the content of the updated archive with the wireshark Git repository at version  v4.4.0 and found no indication of malicious manipulation of the archive.

**Comment by hknaack** [comment]
> ```
> ========================================================================
> Building module wireshark in /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/wireshark-1
> ========================================================================
> �]2;flatpak-builder: Building wireshark�FB: Running: tar xf /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/downloads/ead5cdcc08529a2e7ce291e01defc3b0f8831ba24c938db0762b1ebc59c71269/wireshark-4.4.0.tar.xz --no-same-owner --strip-components=1 -J
> Applying patch 0001-Add-a-developer-name-tag.patch
> FB: Running: patch -p1 -i /srv/buildbot/worker/build-x86_64-7/build/0001-Add-a-developer-name-tag.patch
> patching file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml
> Hunk #1 FAILED at 9.
> 1 out of 1 hunk FAILED -- saving rejects to file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml.rej
> patching file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml
> Hunk #1 FAILED at 9.
> 1 out of 1 hunk FAILED -- saving rejects to file resources/freedesktop/org.wireshark.Wireshark.metainfo.xml.rej
> �]2;flatpak-builder: Cleanup wireshark�Error: module wireshark: Child process exited with code 1
> FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-gNs8SE
> program finished with exit code 1
> ```
> 
> Are the patches upstream?

Yes, 2 out of 3 were backports from upstream and are now obsolete.

**Comment by muelli** [comment]
excellent, thanks!

Have you performed a smoke test whether the app comes up and doesn't crash after some clicking around?

**Comment by hknaack** [comment]
Not yet, got it on my tomorrows agenda.

**Comment by hknaack** [comment]
I have tested it today, it was working without issues.

**Pull request merged**
